version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books_app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"

#  news-service:
#    image: news-service
#    build:
#      context: docker
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SERVER_PORT= 8080
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/news_app
#    depends_on:
#      - postgres